### ISSUE TITLE
failed to read chainxchg response, i/o deadline reached

### ISSUE THREAD

**Issue by christroutner** [textileio/lotus-build#8]
I'm trying to use the `textile/lotus:v1.8.0` Docker image to spin up my own instance of Lotus and Powergate. Here is the [docker-compose.yml file](https://github.com/christroutner/docker-powergate/blob/0d5fdf468432c1c3a54e732153e701ece53a87b9/docker-compose.yml) that I'm using. I'm using the following version of Docker can Docker compose:

- Docker: v20.10.6
- docker-compose v1.27.4

When I run the Lotus image on a Digital Ocean droplet with no firewall, it syncs and stays up just fine. But on my local network, it consistently crashes with the error below. I have ports 4001, 1234, and 5678 port-forwarded on to the machine running the node.

Any idea what the difference is between the setups, and how I can avoid the Lotus container from crashing?

```
...
7m1ZBqsEmiUzz, but remote key matches 12D3KooWDqaZkm3oSczUm3dvAJ5aL2rdSeQ5VQbnHRTQNEFShhmc
2021-05-27T04:46:02.445Z	WARN	peermgr	peermgr/peermgr.go:217	failed to connect to bootstrap peer: failed to dial 12D3KooWQZrGH1PxSNZPum99M1zNvjNFM33d1AAu5DcvdHptuU7u: all dials failed
  * [/ip4/61.147.123.121/tcp/12757] failed to negotiate security protocol: peer id mismatch: expected 12D3KooWQZrGH1PxSNZPum99M1zNvjNFM33d1AAu5DcvdHptuU7u, but remote key matches 12D3KooWDgQrcyZpcMAkbEFSJJYV2qXEMwXX67WTbqpNdbifHaEq
2021-05-27T04:46:02.529Z	WARN	peermgr	peermgr/peermgr.go:217	failed to connect to bootstrap peer: failed to dial 12D3KooWMKxMkD5DMpSWsW7dBddKxKT7L2GgbNuckz9otxvkvByP: all dials failed
  * [/ip4/36.103.232.198/tcp/34723] failed to negotiate security protocol: peer id mismatch: expected 12D3KooWMKxMkD5DMpSWsW7dBddKxKT7L2GgbNuckz9otxvkvByP, but remote key matches 12D3KooWCxT2q9D2DcE7pKv83KyoZhT67jiy1q1PDeFzqmbUvSxY
2021-05-27T04:46:02.638Z	WARN	hello	hello/hello.go:80	other peer has different genesis! (bafy2bzacedmcupeo44orsday5hgxcgyqxh7ooorsxbp7y3sbpthfpsz6jdjoq)
2021-05-27T04:46:03.527Z	INFO	chain	chain/sync_manager.go:218	selected initial sync target: [bafy2bzacedcoanaq4a67mqq77stwxy6lhi7ig64xrea7zsks3p5rtrvipdyr4 bafy2bzacedkxgev2zm6e7xfviavqpapaylnq2boljv7ypanpmmkvsgebabhq4 bafy2bzaced5ybjhhygh7h7izh2cmtiuaweycu7ab6qoxvremnycy74fekuu6e bafy2bzaced77vockqmib76o73g6x5et7bokmc2whqd5frmqwtxh7d6vkevqzi]
2021-05-27T04:46:03.527Z	INFO	chain	chain/sync_manager.go:314	worker 0 syncing in [bafy2bzacedcoanaq4a67mqq77stwxy6lhi7ig64xrea7zsks3p5rtrvipdyr4 bafy2bzacedkxgev2zm6e7xfviavqpapaylnq2boljv7ypanpmmkvsgebabhq4 bafy2bzaced5ybjhhygh7h7izh2cmtiuaweycu7ab6qoxvremnycy74fekuu6e bafy2bzaced77vockqmib76o73g6x5et7bokmc2whqd5frmqwtxh7d6vkevqzi]
2021-05-27T04:46:09.206Z	INFO	chain	chain/sync.go:1352	Got blocks: 792811 500
2021-05-27T04:46:09.280Z	INFO	chain	chain/sync.go:1619	fetching messages at 563
2021-05-27T04:46:09.280Z	INFO	chain	chain/sync.go:1619	fetching messages at 491
2021-05-27T04:46:09.280Z	INFO	chain	chain/sync.go:1619	fetching messages at 443
2021-05-27T04:46:09.280Z	INFO	chain	chain/sync.go:1619	fetching messages at 523
2021-05-27T04:46:09.280Z	INFO	chain	chain/sync.go:1619	fetching messages at 451
2021-05-27T04:46:09.280Z	INFO	chain	chain/sync.go:1619	fetching messages at 515
2021-05-27T04:46:09.280Z	INFO	chain	chain/sync.go:1619	fetching messages at 507
2021-05-27T04:46:09.280Z	INFO	chain	chain/sync.go:1619	fetching messages at 475
2021-05-27T04:46:09.280Z	INFO	chain	chain/sync.go:1619	fetching messages at 459
2021-05-27T04:46:09.281Z	INFO	chain	chain/sync.go:1619	fetching messages at 467
2021-05-27T04:46:09.281Z	INFO	chain	chain/sync.go:1619	fetching messages at 499
2021-05-27T04:46:09.281Z	INFO	chain	chain/sync.go:1619	fetching messages at 483
2021-05-27T04:46:09.281Z	INFO	chain	chain/sync.go:1619	fetching messages at 539
2021-05-27T04:46:09.281Z	INFO	chain	chain/sync.go:1619	fetching messages at 531
2021-05-27T04:46:09.281Z	INFO	chain	chain/sync.go:1619	fetching messages at 555
2021-05-27T04:46:09.281Z	INFO	chain	chain/sync.go:1619	fetching messages at 547
2021-05-27T04:46:18.363Z	WARN	chainxchg	exchange/client.go:119	could not send request to peer 12D3KooWGeBySx4BdUT2wwr7tE4VwnVRdSG2yt1VrBTYqh4XwULc: failed to read chainxchg response: unmarshaling t.Messages pointer: i/o deadline reached
2021-05-27T04:46:18.844Z	WARN	chainxchg	exchange/client.go:119	could not send request to peer 12D3KooWGeBySx4BdUT2wwr7tE4VwnVRdSG2yt1VrBTYqh4XwULc: failed to read chainxchg response: unmarshaling t.Messages pointer: i/o deadline reached
SIGILL: illegal instruction
PC=0x26b2341 m=7 sigcode=2
instruction bytes: 0xc4 0x42 0xbb 0xf6 0xce 0xe8 0x35 0x0 0x0 0x0 0x4c 0x8b 0x7c 0x24 0x18 0x4c

goroutine 0 [idle]:
runtime: unknown pc 0x26b2341
stack: frame={sp:0x7f0dbf7fcf50, fp:0x0} stack=[0x7f0dbeffdea8,0x7f0dbf7fdaa8)
00007f0dbf7fce50:  0000000000000000  0000000000000000 
00007f0dbf7fce60:  0000000000000000  0000000000000000 
00007f0dbf7fce70:  0000000000000000  0000000000000000 
00007f0dbf7fce80:  0000000000000000  0000000000000000 
00007f0dbf7fce90:  0000000000000000  0000000000000000 
...
```

**Comment by jsign** [comment]
The problem is that Lotus needs some CGO dependencies that try to use the same CPU instructions as the machine where the image was built.

You will have to create your own docker-image if you want to run it in that machine.
Basically, you can use this same repo to do that and create the image in your machine and use it.

0. Clone this repo, and also install Lotus dependencies for compiling for your OS https://docs.filecoin.io/get-started/lotus/installation/#minimal-requirements
1. Run `git clone https://github.com/filecoin-project/lotus.git` [yes, in the same folder of this `lotus-build` repo].
2. Go to the `lotus` folder of the cloned repo and `git checkout v1.8.0`
3. Run `RUSTFLAGS="-C target-cpu=native" FFI_BUILD_FROM_SOURCE=1 make deps` [will take a while]
4. Run `cd ..` (go back to `lotus-build` folder).
3. Run `docker build -t lotus:chris .`

So you'll have a new image `lotus:chris` docker image that should run correctly in the same machine you created the image

I'd say that is better to run Lotus natively if you can; in any case you can run it with the docker image in general without problems  (but some times some CPUs don't have the instructions of the images we bake).

**Comment by christroutner** [comment]
Thank you for the explanation and the helpful instructions!

**Comment by christroutner** [comment]
Thank you for the clear instructions @jsign! I created this [bash shell script](https://github.com/christroutner/docker-powergate/blob/40bbce4dd3a654ea0c33fb7dbdb01f60bbdee7f9/lotus-image/build-lotus-image.sh) for building the Docker images, based on your instructions.
